import {
  Terminal,
  Globe,
  Briefcase,
  Users,
  Palette,
  Factory,
  Search,
  Megaphone,
  Building2,
  PenTool,
  FlaskConical,
  Zap,
  Shield,
  FileText,
  BarChart3,
  MessageCircle,
  Brain,
  Gauge,
  Activity,
  Monitor,
  Wrench,
  BookOpen,
  Rocket,
  CircleDot,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const categoryIconMap: Record<string, LucideIcon> = {
  "all":                          CircleDot,
  "coding-clis":                  Terminal,
  "web-browsing":                 Globe,
  "product-business-development": Briefcase,
  "teams-of-agents":              Users,
  "ux-ui":                        Palette,
  "software-factories":           Factory,
  "search-news":                  Search,
  "marketing":                    Megaphone,
  "business":                     Building2,
  "content-writing":              PenTool,
  "research":                     FlaskConical,
  "automation":                   Zap,
  "security":                     Shield,
  "documentation":                FileText,
  "data-analytics":               BarChart3,
  "personal-assistants":          MessageCircle,
  "memory-systems":               Brain,
  "performance":                  Gauge,
  "analytics-llm-tracing":        Activity,
  "web-dev-ui-frameworks":        Monitor,
  "agent-harnesses":              Wrench,
  "knowledge-management":         BookOpen,
  "ai-adoption":                  Rocket,
};
